version: '3.8'

services:
  backend:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:latest
    container_name: backend_db
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: ${POSTGRES_DATA}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: backend_cache
    restart: always
    env_file: .env
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis-data:/data
    command: [ "--requirepass", "${REDIS_PASSWORD}" ]


volumes:
  postgres-data:
  redis-data:
