services:
   postgres:
      image: postgres:latest
      container_name: database
      restart: always
      env_file: .env
      environment:
         POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
         POSTGRES_USER: ${POSTGRES_USER}
         POSTGRES_DB: ${POSTGRES_DB}
         PGDATA: ${POSTGRES_DATA}
      ports:
         - "${POSTGRES_PORT}:${POSTGRES_PORT}"
      expose:
         - "${POSTGRES_PORT}"
      volumes:
         - postgres-data:${POSTGRES_DATA}
   redis:
      image: redis:latest
      container_name: cache
      restart: always
      env_file: .env
      ports:
         - "${REDIS_PORT}:${REDIS_PORT}"
      expose:
         - "${REDIS_PORT}"
      volumes:
         - redis-data:${REDIS_DATA}
      command: [ "--requirepass", "${REDIS_PASSWORD}" ]

   postgres-test:
      image: postgres:latest
      container_name: database_test
      restart: always
      environment:
         POSTGRES_PASSWORD: "testpass"
         POSTGRES_USER: "testuser"
         POSTGRES_DB: "test_db"
      ports:
         - "5433:5432"
      volumes:
         - postgres-test-data:/var/lib/postgresql/data


volumes:
   postgres-data:
   redis-data:
   postgres-test-data:
